export const actions = {
  FETCH_ALL_PRODUCTS: 'FETCH_ALL_PRODUCTS',
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  CART_INCREMENT: 'CART_INCREMENT',
  CART_DECREMENT: 'CART_DECREMENT'
};
  